windowWrap: windowWrap.cpp
	g++ -I C://SFML-2.5.1/include windowWrap.cpp -o windowWrap -L C://SFML-2.5.1/lib -lsfml-graphics -lsfml-window -lsfml-system
runWindowWrap:
	./windowWrap

asteroidsDirection: asteroidsDirection.cpp
	g++ -I C://SFML-2.5.1/include asteroidsDirection.cpp -o asteroidsDirection -L C://SFML-2.5.1/lib -lsfml-graphics -lsfml-window -lsfml-system
runAsteroidsDirection:
	./asteroidsDirection
	
asteroidSpawnCoords: asteroidSpawnCoords.cpp
	g++ -I C://SFML-2.5.1/include asteroidSpawnCoords.cpp -o asteroidSpawnCoords -L C://SFML-2.5.1/lib -lsfml-graphics -lsfml-window -lsfml-system
runAsteroidSpawnCoords:
	./asteroidSpawnCoords

vectorPosition: vectorPosition.cpp
	g++ -I C://SFML-2.5.1/include vectorPosition.cpp -o vectorPosition -L C://SFML-2.5.1/lib -lsfml-graphics -lsfml-window -lsfml-system
runVectorPosition:
	./vectorPosition