windowWrap: windowWrap.cpp
	g++ -g -Wall -I C://SFML-2.5.1/include windowWrap.cpp -o windowWrap -L C://SFML-2.5.1/lib -lsfml-graphics -lsfml-window -lsfml-system
runWindowWrap:
	./windowWrap
asteroidsDirection: asteroidsDirection.cpp
	g++ -g -Wall -I C://SFML-2.5.1/include asteroidsDirection.cpp -o asteroidsDirection -L C://SFML-2.5.1/lib -lsfml-graphics -lsfml-window -lsfml-system
runAsteroidsDirection:
	./asteroidsDirection
	
asteroidSpawnCoords: asteroidSpawnCoords.cpp
	g++ -g -Wall -I C://SFML-2.5.1/include asteroidSpawnCoords.cpp -o asteroidSpawnCoords -L C://SFML-2.5.1/lib -lsfml-graphics -lsfml-window -lsfml-system
runAsteroidSpawnCoords:
	./asteroidSpawnCoords

vectorPosition: vectorPosition.cpp
	g++ -g -Wall -I C://SFML-2.5.1/include vectorPosition.cpp -o vectorPosition -L C://SFML-2.5.1/lib -lsfml-graphics -lsfml-window -lsfml-system
runVectorPosition:
	./vectorPosition
menuChoices: menuValidation.cpp
	g++ -g -Wall menuValidation.cpp -o menuChoices
runMenuChoices:
	./menuChoices < menuChoices.txt
